version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on: [redis]
    volumes:
      - ./worker:/app/worker
      - ./templates:/app/templates